export const brandOptions = [
  { value: "luxury", label: "Luxury" },
  { value: "casualWear", label: "Casual Wear" },
  { value: "formalWear", label: "Formal Wear" },
  { value: "activewear", label: "Activewear/Sportswear" },
  { value: "ethnicWear", label: "Ethnic/Traditional Wear" },
  { value: "denim", label: "Denim" },
  { value: "menWear", label: "Men's Wear" },
  { value: "womenWear", label: "Women's Wear" },
  { value: "kidsWear", label: "Kids' Wear" },
  // { value: "Unisex", label: "Unisex" },
  // { value: "Fast Fashion", label: "Fast Fashion" },
  // { value: "Sustainable", label: "Sustainable/Eco-Friendly" },
  // { value: "Designer", label: "Designer" },
  // { value: "Streetwear", label: "Streetwear" },
  // { value: "Outerwear", label: "Outerwear" },
  // { value: "Underwear", label: "Underwear/Lingerie" },
  // { value: "Accessories", label: "Accessories" },
  // { value: "Athleisure", label: "Athleisure" },
  // { value: "Workwear", label: "Workwear" },
  // { value: "Partywear", label: "Partywear" },
  // { value: "Seasonal Wear", label: "Seasonal Wear" },
  // { value: "Maternity Wear", label: "Maternity Wear" },
  // { value: "Petite", label: "Petite and Plus-Size" },
  // { value: "Vintage", label: "Vintage/Retro" },
];
